name: El Motor de la Mega Maquina

on:
  workflow_dispatch:

jobs:
  arrancar_cerebro:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Extraer archivos
        uses: actions/checkout@v4

      - name: ⚙️ Preparar ordenador virtual
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar librerías
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu fonts-liberation
          pip install pandas groq requests edge-tts moviepy==1.0.3 pillow numpy

      - name: 🚀 Ejecutar Agencia 360 (Todo Español)
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
        run: |
          python main.py

      - name: 🗂️ Entregar Arsenal de Contenido
        uses: actions/upload-artifact@v4
        with:
          name: Paquete_Omnicanal_ES
          path: |
            video_final.mp4
            ig_post_estatico.jpg
            linkedin_carrusel.pdf
            TEXTOS_PARA_REDES.txt
            pines/
