name: El Motor de la Mega Maquina

on:
  workflow_dispatch:

jobs:
  arrancar_cerebro:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Extraer archivos
        uses: actions/checkout@v4

      - name: ⚙️ Preparar ordenador virtual (Python)
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar herramientas multimedia y librerías
        run: |
          sudo apt-get update && sudo apt-get install -y ffmpeg
          pip install pandas groq requests edge-tts moviepy pillow

      - name: 🚀 Ejecutar la Fábrica de Contenido
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          python main.py

      - name: 🗂️ Entregar Vídeos y Textos al Usuario
        uses: actions/upload-artifact@v4
        with:
          name: Paquete_Contenido_Hoy
          path: |
            contenido_hoy.json
            video_final.mp4
